require("dotenv").config();
const bcrypt = require("bcryptjs");
const mongoose = require("mongoose");
const connectDB = require("./config/db");
const User = require("./models/User");
const Article = require("./models/Article");
const Category = require("./models/Category");

const categoriesData = [
  { id: "news", label: "NEWS", slug: "news", parent: null },
  { id: "kerala", label: "Kerala", slug: "kerala", titleMl: "കേരളം", parent: "news" },
  { id: "india", label: "India", slug: "india", titleMl: "ദേശീയം", parent: "news" },
  { id: "world", label: "World", slug: "world", titleMl: "അന്തർദേശീയം", parent: "news" },
  { id: "politics", label: "Politics", slug: "politics", titleMl: "രാഷ്ട്രീയം", parent: "news" },
  { id: "gulf", label: "GULF", slug: "gulf", parent: null },
  { id: "uae", label: "UAE", slug: "uae", titleMl: "യുഎഇ", parent: "gulf" },
  { id: "saudi", label: "Saudi", slug: "saudi", titleMl: "സൗദി", parent: "gulf" },
  { id: "qatar", label: "Qatar", slug: "qatar", titleMl: "ഖത്തർ", parent: "gulf" },
  { id: "pravasi", label: "Pravasi", slug: "pravasi", titleMl: "പ്രവാസി", parent: "gulf" },
  { id: "entertainment", label: "ENTERTAINMENT", slug: "entertainment", parent: null },
  { id: "cinema", label: "Cinema", slug: "cinema", titleMl: "സിനിമ", parent: "entertainment" },
  { id: "music", label: "Music", slug: "music", titleMl: "സംഗീതം", parent: "entertainment" },
  { id: "television", label: "Television", slug: "television", titleMl: "ടെലിവിഷൻ", parent: "entertainment" },
  { id: "sports", label: "SPORTS", slug: "sports", parent: null },
  { id: "football", label: "Football", slug: "football", titleMl: "ഫുട്ബോൾ", parent: "sports" },
  { id: "cricket", label: "Cricket", slug: "cricket", titleMl: "ക്രിക്കറ്റ്", parent: "sports" },
  { id: "other-sports", label: "Other Sports", slug: "other-sports", titleMl: "മറ്റ് കായികം", parent: "sports" },
  { id: "life-style", label: "LIFE STYLE", slug: "life-style", parent: null },
  { id: "health", label: "Health", slug: "health", titleMl: "ആരോഗ്യം", parent: "life-style" },
  { id: "travel", label: "Travel", slug: "travel", titleMl: "യാത്ര", parent: "life-style" },
  { id: "food", label: "Food", slug: "food", titleMl: "ഭക്ഷണം", parent: "life-style" },
  { id: "multi-media", label: "MULTI MEDIA", slug: "multi-media", parent: null },
  { id: "photos", label: "Photos", slug: "photos", titleMl: "ഫോട്ടോകൾ", parent: "multi-media" },
  { id: "videos", label: "Videos", slug: "videos", titleMl: "വീഡിയോകൾ", parent: "multi-media" },
  { id: "audio", label: "Audio", slug: "audio", titleMl: "ഓഡിയോ", parent: "multi-media" },
  { id: "veedu", label: "VEEDU", slug: "veedu", parent: null },
  { id: "veedu-home", label: "Home", slug: "veedu-home", titleMl: "വീട്", parent: "veedu" },
  { id: "property", label: "Property", slug: "property", titleMl: "പ്രോപ്പർട്ടി", parent: "veedu" },
  { id: "garden", label: "Garden", slug: "garden", titleMl: "തോട്ടം", parent: "veedu" },
  { id: "column", label: "COLUMN", slug: "column", parent: null },
  { id: "opinion", label: "Opinion", slug: "opinion", titleMl: "അഭിപ്രായം", parent: "column" },
  { id: "editorial", label: "Editorial", slug: "editorial", titleMl: "എഡിറ്റോറിയൽ", parent: "column" },
  { id: "readers", label: "Readers", slug: "readers", titleMl: "വായനക്കാർ", parent: "column" },
  { id: "more", label: "MORE", slug: "more", parent: null },
  { id: "business", label: "Business", slug: "business", titleMl: "ബിസിനസ്", parent: "more" },
  { id: "tech", label: "Tech", slug: "tech", titleMl: "സാങ്കേതികം", parent: "more" },
  { id: "education", label: "Education", slug: "education", titleMl: "വിദ്യാഭ്യാസം", parent: "more" },
];

const articlesData = [
  {
    slug: "rain-alert-kerala-coast",
    title: "തീരദേശത്ത് മഴ കനക്കും; അഞ്ച് ജില്ലകളിൽ പ്രത്യേക ജാഗ്രത",
    titleEn: "Heavy Rain Alert on Kerala Coast: Fishing Ban Imposed",
    category: "kerala",
    categoryMl: "കേരളം",
    author: "മലയാളമിത്രം ഡെസ്ക്",
    image: "/uploads/1785497475755-p42a8g.jpeg",
    featured: true,
    media: "standard",
    excerpt: "കടൽക്ഷോഭ സാധ്യത കണക്കിലെടുത്ത് മത്സ്യത്തൊഴിലാളികൾക്കും തീരദേശവാസികൾക്കും പുതുക്കിയ മുന്നറിയിപ്പ് നൽകി.",
    content: "സംസ്ഥാനത്ത് മൺസൂൺ സജീവമായതോടെ തീരദേശ മേഖലകളിൽ ശക്തമായ മഴക്കും കാറ്റിനും സാധ്യതയുണ്ടെന്ന് കാലാവസ്ഥാ വിഭാഗം അറിയിച്ചു. അത്യാവശ്യ ഘട്ടങ്ങളിൽ മാത്രം യാത്ര ചെയ്യണമെന്നും ഔദ്യോഗിക അറിയിപ്പുകൾ ശ്രദ്ധിക്കണമെന്നും ദുരന്തനിവാരണ അതോറിറ്റി നിർദ്ദേശിച്ചു.",
    body: ["സംസ്ഥാനത്ത് മൺസൂൺ സജീവമായതോടെ തീരദേശ മേഖലകളിൽ ശക്തമായ മഴക്കും കാറ്റിനും സാധ്യതയുണ്ടെന്ന് കാലാവസ്ഥാ വിഭാഗം അറിയിച്ചു.", "അത്യാവശ്യ ഘട്ടങ്ങളിൽ മാത്രം യാത്ര ചെയ്യണമെന്നും ഔദ്യോഗിക അറിയിപ്പുകൾ ശ്രദ്ധിക്കണമെന്നും ദുരന്തനിവാരണ അതോറിറ്റി നിർദ്ദേശിച്ചു."],
    tags: ["മഴ", "കേരളം", "ജാഗ്രത"],
    readTime: "4 മിനിറ്റ്",
    comments: 24,
  },
  {
    slug: "delhi-policy-meeting",
    title: "കേന്ദ്ര പദ്ധതികളുടെ അവലോകനം: സംസ്ഥാനങ്ങൾക്ക് കൂടുതൽ ഫണ്ട് ആവശ്യപ്പെട്ട് യോഗം",
    titleEn: "National Policy Meeting in Delhi: Kerala Minister Attends",
    category: "india",
    categoryMl: "ദേശീയം",
    author: "ദേശീയ ലേഖകൻ",
    image: "/uploads/1785497610003-v478hm.jpg",
    featured: true,
    media: "standard",
    excerpt: "അടിസ്ഥാന സൗകര്യം, ആരോഗ്യ മേഖല, തൊഴിൽ പരിശീലനം എന്നിവയ്ക്ക് പ്രത്യേക പാക്കേജ് വേണമെന്ന ആവശ്യം ഉയർന്നു.",
    content: "വിവിധ സംസ്ഥാനങ്ങളുടെ വികസന ആവശ്യങ്ങൾ ഉൾപ്പെടുത്തി കേന്ദ്രതല യോഗത്തിൽ വിശദമായ ചർച്ച നടന്നു. പദ്ധതി വിനിയോഗത്തിലെ സുതാര്യത വർധിപ്പിക്കാൻ ഡിജിറ്റൽ നിരീക്ഷണ സംവിധാനം ശക്തമാക്കും.",
    body: ["വിവിധ സംസ്ഥാനങ്ങളുടെ വികസന ആവശ്യങ്ങൾ ഉൾപ്പെടുത്തി കേന്ദ്രതല യോഗത്തിൽ വിശദമായ ചർച്ച നടന്നു.", "പദ്ധതി വിനിയോഗത്തിലെ സുതാര്യത വർധിപ്പിക്കാൻ ഡിജിറ്റൽ നിരീക്ഷണ സംവിധാനം ശക്തമാക്കും."],
    tags: ["ഇന്ത്യ", "വികസനം", "പദ്ധതി"],
    readTime: "3 മിനിറ്റ്",
    comments: 13,
  },
  {
    slug: "gulf-expat-services",
    title: "പ്രവാസികൾക്കായി ഗൾഫ് ഹെൽപ്പ് ഡെസ്ക് സേവനങ്ങൾ വിപുലീകരിക്കുന്നു",
    category: "pravasi",
    categoryMl: "പ്രവാസി",
    author: "പ്രവാസി വാർത്താ വിഭാഗം",
    image: "/uploads/1785497717341-u8h7lq.jpg",
    featured: false,
    media: "standard",
    excerpt: "രേഖാപരമായ സഹായം, തൊഴിൽ പരാതികൾ, യാത്രാ നിർദ്ദേശങ്ങൾ എന്നിവ ഒരുമിച്ച് ലഭ്യമാക്കുന്ന സംവിധാനം ശക്തമാക്കുന്നു.",
    content: "ഗൾഫ് രാജ്യങ്ങളിലെ മലയാളികൾക്ക് വേഗത്തിൽ സേവനം ലഭ്യമാക്കാൻ ഹെൽപ്പ് ഡെസ്കുകളുടെ പ്രവർത്തന സമയം വർധിപ്പിക്കും. പ്രവാസി സംഘടനകളുമായി സഹകരിച്ച് ക്യാമ്പുകളും ഡിജിറ്റൽ രജിസ്ട്രേഷൻ സംവിധാനവും ഒരുക്കും.",
    body: ["ഗൾഫ് രാജ്യങ്ങളിലെ മലയാളികൾക്ക് വേഗത്തിൽ സേവനം ലഭ്യമാക്കാൻ ഹെൽപ്പ് ഡെസ്കുകളുടെ പ്രവർത്തന സമയം വർധിപ്പിക്കും.", "പ്രവാസി സംഘടനകളുമായി സഹകരിച്ച് ക്യാമ്പുകളും ഡിജിറ്റൽ രജിസ്ട്രേഷൻ സംവിധാനവും ഒരുക്കും."],
    tags: ["ഗൾഫ്", "പ്രവാസി", "സേവനം"],
    readTime: "5 മിനിറ്റ്",
    comments: 18,
  },
  {
    slug: "uae-summer-travel",
    title: "യുഎഇയിൽ വേനൽ യാത്രാ തിരക്ക്; വിമാന നിരക്കിൽ വർധന",
    category: "uae",
    categoryMl: "യുഎഇ",
    author: "ഗൾഫ് ലേഖകൻ",
    image: "/uploads/1785497721731-6q2k9s.jpg",
    featured: false,
    media: "photo",
    excerpt: "അവധി സീസൺ തുടങ്ങുന്നതോടെ കേരളത്തിലേക്കുള്ള ടിക്കറ്റുകൾക്ക് ആവശ്യക്കാരേറി.",
    content: "വിമാന കമ്പനികൾ അധിക സർവീസുകൾ പരിഗണിക്കുന്നതായി ട്രാവൽ ഏജൻസികൾ അറിയിച്ചു. യാത്രക്കാർ മുൻകൂട്ടി ബുക്കിംഗ് നടത്തണമെന്ന് നിർദ്ദേശമുണ്ട്.",
    body: ["വിമാന കമ്പനികൾ അധിക സർവീസുകൾ പരിഗണിക്കുന്നതായി ട്രാവൽ ഏജൻസികൾ അറിയിച്ചു.", "യാത്രക്കാർ മുൻകൂട്ടി ബുക്കിംഗ് നടത്തണമെന്ന് നിർദ്ദേശമുണ്ട്."],
    tags: ["യുഎഇ", "യാത്ര", "പ്രവാസി"],
    readTime: "3 മിനിറ്റ്",
    comments: 8,
  },
  {
    slug: "global-climate-summit",
    title: "കാലാവസ്ഥാ ഉച്ചകോടി: തീര നഗരങ്ങൾക്ക് പുതിയ സംരക്ഷണ പദ്ധതി",
    category: "world",
    categoryMl: "അന്തർദേശീയം",
    author: "ലോക വാർത്താ ഡെസ്ക്",
    image: "/uploads/1785500250906-2dxkv2.png",
    featured: false,
    media: "standard",
    excerpt: "കടൽനിരപ്പ് ഉയരുന്ന നഗരങ്ങൾക്ക് സാമ്പത്തിക പിന്തുണയും സാങ്കേതിക സഹായവും നൽകുന്ന നിർദ്ദേശം ചർച്ചയായി.",
    content: "വിവിധ രാജ്യങ്ങളുടെ പ്രതിനിധികൾ പങ്കെടുത്ത ഉച്ചകോടിയിൽ തീരദേശ സുരക്ഷ പ്രധാന വിഷയമായി. താഴ്ന്ന വരുമാന രാജ്യങ്ങൾക്ക് പ്രത്യേക സഹായ ഫണ്ടിനുള്ള നിർദ്ദേശവും പിന്തുണ നേടി.",
    body: ["വിവിധ രാജ്യങ്ങളുടെ പ്രതിനിധികൾ പങ്കെടുത്ത ഉച്ചകോടിയിൽ തീരദേശ സുരക്ഷ പ്രധാന വിഷയമായി.", "താഴ്ന്ന വരുമാന രാജ്യങ്ങൾക്ക് പ്രത്യേക സഹായ ഫണ്ടിനുള്ള നിർദ്ദേശവും പിന്തുണ നേടി."],
    tags: ["ലോകം", "കാലാവസ്ഥ", "തീരദേശം"],
    readTime: "4 മിനിറ്റ്",
    comments: 9,
  },
  {
    slug: "kochi-startup-fund",
    title: "കൊച്ചി സ്റ്റാർട്ടപ്പുകൾക്ക് പുതിയ നിക്ഷേപ വാതിൽ തുറക്കുന്നു",
    category: "business",
    categoryMl: "ബിസിനസ്",
    author: "ബിസിനസ് ലേഖകൻ",
    image: "/uploads/1785502076693-djq4b0.png",
    featured: false,
    media: "standard",
    excerpt: "ഫിൻടെക്, ഹെൽത്ത് ടെക്, ക്ലൈമറ്റ് ടെക് മേഖലകളിലെ സംരംഭങ്ങൾക്കാണ് ആദ്യ ഘട്ടത്തിൽ മുൻഗണന.",
    content: "പ്രാദേശിക സംരംഭങ്ങൾക്കു വിപണി പ്രവേശനവും നിക്ഷേപകരുമായി ബന്ധപ്പെടാനുള്ള അവസരവും നൽകുന്ന പദ്ധതിയാണ് പ്രഖ്യാപിച്ചത്. സംരംഭകർക്ക് മാർഗനിർദ്ദേശം, നിയമസഹായം, ബ്രാൻഡിംഗ് പിന്തുണ എന്നിവയും പാക്കേജിൽ ഉൾപ്പെടും.",
    body: ["പ്രാദേശിക സംരംഭങ്ങൾക്കു വിപണി പ്രവേശനവും നിക്ഷേപകരുമായി ബന്ധപ്പെടാനുള്ള അവസരവും നൽകുന്ന പദ്ധതിയാണ് പ്രഖ്യാപിച്ചത്.", "സംരംഭകർക്ക് മാർഗനിർദ്ദേശം, നിയമസഹായം, ബ്രാൻഡിംഗ് പിന്തുണ എന്നിവയും പാക്കേജിൽ ഉൾപ്പെടും."],
    tags: ["സ്റ്റാർട്ടപ്പ്", "കൊച്ചി", "നിക്ഷേപം"],
    readTime: "5 മിനിറ്റ്",
    comments: 7,
  },
  {
    slug: "football-final-training",
    title: "ഫൈനലിന് മുമ്പ് അവസാന പരിശീലനം; ആരാധകർ ആവേശത്തിൽ",
    category: "football",
    categoryMl: "ഫുട്ബോൾ",
    author: "സ്പോർട്സ് ഡെസ്ക്",
    image: "/uploads/1785561019451-jpqyub.png",
    featured: false,
    media: "video",
    excerpt: "പ്രതിരോധ ശക്തിയും വേഗമേറിയ ആക്രമണവും ഫൈനലിന്റെ ഗതി മാറ്റുമെന്നാണ് പരിശീലകരുടെ വിലയിരുത്തൽ.",
    content: "ഇരു ടീമുകളും പരിശീലനം പൂർത്തിയാക്കി തന്ത്രങ്ങൾ അന്തിമമാക്കി. സ്റ്റേഡിയം പ്രവേശനത്തിന് പ്രത്യേക ഗതാഗത ക്രമീകരണങ്ങളും സുരക്ഷാ മാർഗനിർദ്ദേശങ്ങളും പ്രഖ്യാപിച്ചു.",
    body: ["ഇരു ടീമുകളും പരിശീലനം പൂർത്തിയാക്കി തന്ത്രങ്ങൾ അന്തിമമാക്കി.", "സ്റ്റേഡിയം പ്രവേശനത്തിന് പ്രത്യേക ഗതാഗത ക്രമീകരണങ്ങളും സുരക്ഷാ മാർഗനിർദ്ദേശങ്ങളും പ്രഖ്യാപിച്ചു."],
    tags: ["ഫുട്ബോൾ", "ഫൈനൽ", "കായികം"],
    readTime: "2 മിനിറ്റ്",
    comments: 31,
  },
  {
    slug: "cricket-team-update",
    title: "ക്രിക്കറ്റ് ടീമിൽ യുവതാരങ്ങൾക്ക് അവസരം; പ്രഖ്യാപനം ഉടൻ",
    category: "cricket",
    categoryMl: "ക്രിക്കറ്റ്",
    author: "കായിക റിപ്പോർട്ടർ",
    image: "/uploads/1785561024128-0m23yz.jpeg",
    featured: false,
    media: "standard",
    excerpt: "വരാനിരിക്കുന്ന പരമ്പരയ്ക്കായി സെലക്ഷൻ കമ്മിറ്റി പുതുമുഖങ്ങളെ പരിഗണിക്കുന്നു.",
    content: "ദേശീയ ലീഗിലെ പ്രകടനമാണ് യുവതാരങ്ങൾക്ക് വഴി തുറന്നത്. അന്തിമ പട്ടിക ഈ ആഴ്ച അവസാനം പുറത്തുവരും.",
    body: ["ദേശീയ ലീഗിലെ പ്രകടനമാണ് യുവതാരങ്ങൾക്ക് വഴി തുറന്നത്.", "അന്തിമ പട്ടിക ഈ ആഴ്ച അവസാനം പുറത്തുവരും."],
    tags: ["ക്രിക്കറ്റ്", "ടീം", "കായികം"],
    readTime: "3 മിനിറ്റ്",
    comments: 14,
  },
  {
    slug: "malayalam-ai-tools",
    title: "മലയാളം ഉള്ളടക്ക നിർമ്മാണത്തിന് പുതിയ എഐ ഉപകരണങ്ങൾ ശ്രദ്ധ നേടുന്നു",
    category: "tech",
    categoryMl: "സാങ്കേതികം",
    author: "ടെക് റിപ്പോർട്ടർ",
    image: "/uploads/1785561028892-wonufo.png",
    featured: false,
    media: "standard",
    excerpt: "വാർത്താ മുറികൾക്കും വിദ്യാഭ്യാസ മേഖലയ്ക്കും മലയാളത്തിൽ വേഗത്തിൽ ഉള്ളടക്കം തയ്യാറാക്കാൻ സഹായിക്കുന്ന ഉപകരണങ്ങൾ വളരുന്നു.",
    content: "ശബ്ദം തിരിച്ചറിയൽ, ലിപ്യന്തരണം, പിശക് തിരുത്തൽ തുടങ്ങിയ മേഖലകളിൽ മലയാളം പിന്തുണ മെച്ചപ്പെടുന്നു. സ്വകാര്യതയും വിവരസുരക്ഷയും ഉറപ്പാക്കുന്ന രീതിയിൽ ഉപകരണങ്ങൾ ഉപയോഗിക്കണമെന്ന് വിദഗ്ധർ നിർദ്ദേശിക്കുന്നു.",
    body: ["ശബ്ദം തിരിച്ചറിയൽ, ലിപ്യന്തരണം, പിശക് തിരുത്തൽ തുടങ്ങിയ മേഖലകളിൽ മലയാളം പിന്തുണ മെച്ചപ്പെടുന്നു.", "സ്വകാര്യതയും വിവരസുരക്ഷയും ഉറപ്പാക്കുന്ന രീതിയിൽ ഉപകരണങ്ങൾ ഉപയോഗിക്കണമെന്ന് വിദഗ്ധർ നിർദ്ദേശിക്കുന്നു."],
    tags: ["എഐ", "മലയാളം", "ടെക്"],
    readTime: "4 മിനിറ്റ്",
    comments: 16,
  },
  {
    slug: "cinema-release-weekend",
    title: "വാരാന്ത്യ റിലീസുകൾ: തിയേറ്ററുകളിൽ മൂന്ന് മലയാള ചിത്രങ്ങൾ",
    category: "cinema",
    categoryMl: "സിനിമ",
    author: "വിനോദം ഡെസ്ക്",
    image: "/uploads/1785561065753-82iat6.jpeg",
    featured: false,
    media: "photo",
    excerpt: "കുടുംബ പ്രേക്ഷകരെയും യുവാക്കളെയും ലക്ഷ്യമിട്ട് വ്യത്യസ്ത സ്വഭാവമുള്ള ചിത്രങ്ങളാണ് പ്രദർശനത്തിനെത്തുന്നത്.",
    content: "പ്രിവ്യൂ പ്രദർശനങ്ങൾക്ക് ശേഷം മികച്ച പ്രതികരണമാണ് ലഭിച്ചതെന്ന് നിർമാതാക്കൾ പറയുന്നു. ചിത്രങ്ങളുടെ വിശദമായ നിരൂപണവും ബോക്സ് ഓഫീസ് റിപ്പോർട്ടും മലയാളമിത്രത്തിൽ പ്രസിദ്ധീകരിക്കും.",
    body: ["പ്രിവ്യൂ പ്രദർശനങ്ങൾക്ക് ശേഷം മികച്ച പ്രതികരണമാണ് ലഭിച്ചതെന്ന് നിർമാതാക്കൾ പറയുന്നു.", "ചിത്രങ്ങളുടെ വിശദമായ നിരൂപണവും ബോക്സ് ഓഫീസ് റിപ്പോർട്ടും മലയാളമിത്രത്തിൽ പ്രസിദ്ധീകരിക്കും."],
    tags: ["സിനിമ", "റിലീസ്", "വിനോദം"],
    readTime: "3 മിനിറ്റ്",
    comments: 12,
  },
  {
    slug: "health-morning-habits",
    title: "പ്രഭാത ശീലങ്ങൾ മാറ്റിയാൽ ആരോഗ്യത്തിൽ വലിയ മാറ്റം",
    category: "health",
    categoryMl: "ആരോഗ്യം",
    author: "ലൈഫ് സ്റ്റൈൽ ഡെസ്ക്",
    image: "/uploads/1783163244674-te9wo4.jpg",
    featured: false,
    media: "standard",
    excerpt: "ഉറക്കം, വെള്ളം, ലഘു വ്യായാമം എന്നിവ ചേർന്ന ചെറിയ ക്രമീകരണങ്ങൾ ശരീരത്തിന് സഹായകരമാകാം.",
    content: "ദിവസാരംഭത്തിലെ ചെറിയ ശീലങ്ങൾ ശരീര ഊർജത്തെയും മാനസികാവസ്ഥയെയും സ്വാധീനിക്കുന്നു. ആരോഗ്യ പ്രശ്നങ്ങളുള്ളവർ ഡോക്ടറുടെ നിർദ്ദേശം തേടിയ ശേഷം മാറ്റങ്ങൾ വരുത്തണം.",
    body: ["ദിവസാരംഭത്തിലെ ചെറിയ ശീലങ്ങൾ ശരീര ഊർജത്തെയും മാനസികാവസ്ഥയെയും സ്വാധീനിക്കുന്നു.", "ആരോഗ്യ പ്രശ്നങ്ങളുള്ളവർ ഡോക്ടറുടെ നിർദ്ദേശം തേടിയ ശേഷം മാറ്റങ്ങൾ വരുത്തണം."],
    tags: ["ആരോഗ്യം", "ലൈഫ് സ്റ്റൈൽ"],
    readTime: "3 മിനിറ്റ്",
    comments: 6,
  },
  {
    slug: "veedu-property-guide",
    title: "വീട് വാങ്ങുമ്പോൾ ശ്രദ്ധിക്കേണ്ട രേഖകളും പരിശോധനകളും",
    category: "property",
    categoryMl: "പ്രോപ്പർട്ടി",
    author: "വീട് വിഭാഗം",
    image: "/uploads/1783163183170-gk3kw5.jpeg",
    featured: false,
    media: "standard",
    excerpt: "സ്ഥല രേഖകൾ മുതൽ കെട്ടിട അനുമതി വരെ പരിശോധിക്കാതെ കരാർ ഒപ്പിടരുതെന്ന് വിദഗ്ധർ പറയുന്നു.",
    content: "വീട് വാങ്ങൽ കുടുംബത്തിന്റെ വലിയ സാമ്പത്തിക തീരുമാനങ്ങളിലൊന്നാണ്. നിയമപരമായ പരിശോധനകൾക്കൊപ്പം പ്രദേശത്തിന്റെ സൗകര്യങ്ങളും ഭാവി വികസനവും വിലയിരുത്തണം.",
    body: ["വീട് വാങ്ങൽ കുടുംബത്തിന്റെ വലിയ സാമ്പത്തിക തീരുമാനങ്ങളിലൊന്നാണ്.", "നിയമപരമായ പരിശോധനകൾക്കൊപ്പം പ്രദേശത്തിന്റെ സൗകര്യങ്ങളും ഭാവി വികസനവും വിലയിരുത്തണം."],
    tags: ["വീട്", "പ്രോപ്പർട്ടി"],
    readTime: "5 മിനിറ്റ്",
    comments: 10,
  },
  {
    slug: "editorial-city-planning",
    title: "നഗര വളർച്ചയ്ക്ക് മനുഷ്യസൗഹൃദ പദ്ധതിയിടൽ വേണം",
    category: "editorial",
    categoryMl: "എഡിറ്റോറിയൽ",
    author: "എഡിറ്റോറിയൽ ബോർഡ്",
    image: "/uploads/1783160388609-7zw5ly.jpeg",
    featured: false,
    media: "standard",
    excerpt: "റോഡ്, വെള്ളം, മാലിന്യസംസ്കരണം, പൊതുഗതാഗതം എന്നിവ ഒന്നിച്ച് ചിന്തിച്ചാലേ നഗരങ്ങൾ ജീവിക്കാൻ സൗകര്യമുള്ളതാകൂ.",
    content: "വേഗത്തിൽ വളരുന്ന നഗരങ്ങൾക്കു പദ്ധതിയിടലിലെ ഏകോപനം അനിവാര്യമാണ്. ജനപങ്കാളിത്തം കൂടാതെ ചെയ്യുന്ന വികസന പ്രവർത്തനങ്ങൾ ദീർഘകാലത്ത് പ്രശ്നങ്ങൾ സൃഷ്ടിക്കും.",
    body: ["വേഗത്തിൽ വളരുന്ന നഗരങ്ങൾക്കു പദ്ധതിയിടലിലെ ഏകോപനം അനിവാര്യമാണ്.", "ജനപങ്കാളിത്തം കൂടാതെ ചെയ്യുന്ന വികസന പ്രവർത്തനങ്ങൾ ദീർഘകാലത്ത് പ്രശ്നങ്ങൾ സൃഷ്ടിക്കും."],
    tags: ["എഡിറ്റോറിയൽ", "നഗരം"],
    readTime: "4 മിനിറ്റ്",
    comments: 5,
  },
  {
    slug: "india-budget-session",
    title: "ഇന്ത്യൻ ബഡ്ജറ്റ് സമ്മേളനം: നികുതി പരിഷ്കരണം പ്രഖ്യാപിച്ചു",
    titleEn: "India Budget Session: Tax Reform Announced",
    category: "india",
    categoryMl: "ദേശീയം",
    author: "ദേശീയ ലേഖകൻ",
    image: "/uploads/1783142040834-o2oq27.png",
    featured: false,
    media: "standard",
    excerpt: "ഇന്ത്യൻ ബഡ്ജറ്റിൽ നികുതി പരിഷ്കരണം പ്രഖ്യാപിച്ചു. സാധാരണക്കാർക്ക് ഇളവുകൾ പ്രഖ്യാപിച്ചു.",
    content: "കേന്ദ്ര ബഡ്ജറ്റിൽ നികുതി ഇളവുകൾ പ്രഖ്യാപിച്ചു. മധ്യവർഗത്തിന് വലിയ ആശ്വാസം.",
    body: ["കേന്ദ്ര ബഡ്ജറ്റിൽ നികുതി ഇളവുകൾ പ്രഖ്യാപിച്ചു."],
    tags: ["ഇന്ത്യ", "ബഡ്ജറ്റ്", "നികുതി"],
    readTime: "4 മിനിറ്റ്",
    comments: 15,
  },
  {
    slug: "india-space-launch",
    title: "ഇസ്റോ ചന്ദ്രയാൻ-4 ദൗത്യം പ്രഖ്യാപിച്ചു",
    titleEn: "ISRO Announces Chandrayaan-4 Mission",
    category: "india",
    categoryMl: "ദേശീയം",
    author: "ദേശീയ ലേഖകൻ",
    image: "/uploads/1783079675331-7p6a5s.png",
    featured: false,
    media: "standard",
    excerpt: "ഇസ്റോ ചന്ദ്രയാൻ-4 ദൗത്യം ഔദ്യോഗികമായി പ്രഖ്യാപിച്ചു.",
    content: "ഇന്ത്യയുടെ അടുത്ത ചന്ദ്ര ദൗത്യം ഔദ്യോഗികമായി പ്രഖ്യാപിച്ചു.",
    body: ["ഇന്ത്യയുടെ അടുത്ത ചന്ദ്ര ദൗത്യം ഔദ്യോഗികമായി പ്രഖ്യാപിച്ചു."],
    tags: ["ഇന്ത്യ", "ബഹിരാകാശം", "ഇസ്റോ"],
    readTime: "4 മിനിറ്റ്",
    comments: 22,
  },
  {
    slug: "india-railway-project",
    title: "ഇന്ത്യയിൽ ബുള്ളറ്റ് ട്രെയിൻ പദ്ധതി വേഗത്തിൽ",
    titleEn: "India Bullet Train Project Accelerates",
    category: "india",
    categoryMl: "ദേശീയം",
    author: "ദേശീയ ലേഖകൻ",
    image: "/uploads/1785502076693-djq4b0.png",
    featured: false,
    media: "standard",
    excerpt: "ബുള്ളറ്റ് ട്രെയിൻ പദ്ധതിയുടെ നിർമ്മാണം വേഗത്തിലാക്കി.",
    content: "മുംബൈ-അഹമ്മദാബാദ് ബുള്ളറ്റ് ട്രെയിൻ പദ്ധതി അടുത്ത ഘട്ടത്തിൽ.",
    body: ["മുംബൈ-അഹമ്മദാബാദ് ബുള്ളറ്റ് ട്രെയിൻ പദ്ധതി അടുത്ത ഘട്ടത്തിൽ."],
    tags: ["ഇന്ത്യ", "ഗതാഗതം", "ട്രെയിൻ"],
    readTime: "3 മിനിറ്റ്",
    comments: 11,
  },
  {
    slug: "india-digital-india",
    title: "ഡിജിറ്റൽ ഇന്ത്യ: പുതിയ സംവിധാനം പ്രവർത്തനക്ഷമമായി",
    titleEn: "Digital India: New System Becomes Operational",
    category: "india",
    categoryMl: "ദേശീയം",
    author: "ദേശീയ ലേഖകൻ",
    image: "/uploads/1783079665441-tkx6gf.png",
    featured: false,
    media: "standard",
    excerpt: "ഡിജിറ്റൽ ഇന്ത്യ പദ്ധതിയുടെ ഭാഗമായി പുതിയ സംവിധാനം പ്രവർത്തനക്ഷമമായി.",
    content: "സർക്കാർ സേവനങ്ങൾ ഡിജിറ്റലൈസ് ചെയ്യുന്നതിന് പുതിയ സംവിധാനം ആരംഭിച്ചു.",
    body: ["സർക്കാർ സേവനങ്ങൾ ഡിജിറ്റലൈസ് ചെയ്യുന്നതിന് പുതിയ സംവിധാനം ആരംഭിച്ചു."],
    tags: ["ഇന്ത്യ", "ടെക്", "ഡിജിറ്റൽ"],
    readTime: "3 മിനിറ്റ്",
    comments: 9,
  },
  {
    slug: "india-defense-deal",
    title: "ഇന്ത്യയുടെ പ്രതിരോധ കരാർ: പുതിയ യുദ്ധവിമാനം ലഭിക്കും",
    titleEn: "India Defense Deal: New Fighter Jet Coming",
    category: "india",
    categoryMl: "ദേശീയം",
    author: "ദേശീയ ലേഖകൻ",
    image: "/uploads/1783142040834-o2oq27.png",
    featured: false,
    media: "standard",
    excerpt: "ഇന്ത്യൻ പ്രതിരോധ മന്ത്രാലയം പുതിയ യുദ്ധവിമാന കരാർ ഒപ്പിട്ടു.",
    content: "പ്രതിരോധ സേനയ്ക്ക് പുതിയ യുദ്ധവിമാനം ലഭിക്കും.",
    body: ["പ്രതിരോധ സേനയ്ക്ക് പുതിയ യുദ്ധവിമാനം ലഭിക്കും."],
    tags: ["ഇന്ത്യ", "പ്രതിരോധം"],
    readTime: "4 മിനിറ്റ്",
    comments: 18,
  },
  {
    slug: "world-economic-forum",
    title: "ലോക സാമ്പത്തിക ഫോറം: പ്രധാന തീരുമാനങ്ങൾ പുറത്തുവന്നു",
    titleEn: "World Economic Forum: Key Decisions Released",
    category: "world",
    categoryMl: "അന്തർദേശീയം",
    author: "ലോക വാർത്താ ഡെസ്ക്",
    image: "/uploads/1783079655635-xguy6s.png",
    featured: false,
    media: "standard",
    excerpt: "ഡാവോസിൽ നടന്ന ലോക സാമ്പത്തിക ഫോറത്തിൽ പ്രധാന തീരുമാനങ്ങൾ.",
    content: "ലോക സാമ്പത്തിക ഫോറത്തിൽ വിവിധ വിഷയങ്ങൾ ചർച്ച ചെയ്തു.",
    body: ["ലോക സാമ്പത്തിക ഫോറത്തിൽ വിവിധ വിഷയങ്ങൾ ചർച്ച ചെയ്തു."],
    tags: ["ലോകം", "സാമ്പത്തികം", "ഫോറം"],
    readTime: "4 മിനിറ്റ്",
    comments: 10,
  },
  {
    slug: "world-climate-agreement",
    title: "ലോക കാലാവസ്ഥ ഉടമ്പടി: പുതിയ ലക്ഷ്യം നിശ്ചയിച്ചു",
    titleEn: "Global Climate Agreement: New Target Set",
    category: "world",
    categoryMl: "അന്തർദേശീയം",
    author: "ലോക വാർത്താ ഡെസ്ക്",
    image: "/uploads/1783079636218-3n5wer.png",
    featured: false,
    media: "standard",
    excerpt: "കാർബൺ ഉദ്‌വമനം കുറയ്ക്കാൻ പുതിയ ലക്ഷ്യം നിശ്ചയിച്ചു.",
    content: "പാരിസ് ഉടമ്പടിയുടെ ഭാഗമായി പുതിയ കാലാവസ്ഥ ലക്ഷ്യം.",
    body: ["പാരിസ് ഉടമ്പടിയുടെ ഭാഗമായി പുതിയ കാലാവസ്ഥ ലക്ഷ്യം."],
    tags: ["ലോകം", "കാലാവസ്ഥ", "ഉടമ്പടി"],
    readTime: "4 മിനിറ്റ്",
    comments: 8,
  },
  {
    slug: "world-un-meeting",
    title: "യുഎൻ ജനറൽ അസംബ്ലി: സമാധാനത്തിന് ആഹ്വാനം",
    titleEn: "UN General Assembly: Call for Peace",
    category: "world",
    categoryMl: "അന്തർദേശീയം",
    author: "ലോക വാർത്താ ഡെസ്ക്",
    image: "/uploads/1783056768628-wf4il5.png",
    featured: false,
    media: "standard",
    excerpt: "യുഎൻ ജനറൽ അസംബ്ലിയിൽ ലോക സമാധാനത്തിന് ആഹ്വാനം.",
    content: "യുഎൻ ജനറൽ അസംബ്ലിയിൽ ഇന്ത്യ സമാധാനത്തിന് ആഹ്വാനം ചെയ്തു.",
    body: ["യുഎൻ ജനറൽ അസംബ്ലിയിൽ ഇന്ത്യ സമാധാനത്തിന് ആഹ്വാനം ചെയ്തു."],
    tags: ["ലോകം", "യുഎൻ", "സമാധാനം"],
    readTime: "4 മിനിറ്റ്",
    comments: 12,
  },
  {
    slug: "world-space-station",
    title: "അന്താരാഷ്ട്ര ബഹിരാകാശ നിലയം: പുതിയ മൊഡ്യൂൾ",
    titleEn: "International Space Station: New Module",
    category: "world",
    categoryMl: "അന്തർദേശീയം",
    author: "ലോക വാർത്താ ഡെസ്ക്",
    image: "/uploads/1785561028892-wonufo.png",
    featured: false,
    media: "standard",
    excerpt: "അന്താരാഷ്ട്ര ബഹിരാകാശ നിലയത്തിന് പുതിയ ഗവേഷണ മൊഡ്യൂൾ.",
    content: "ബഹിരാകാശ നിലയത്തിൽ പുതിയ ഗവേഷണ മൊഡ്യൂൾ സ്ഥാപിക്കും.",
    body: ["ബഹിരാകാശ നിലയത്തിൽ പുതിയ ഗവേഷണ മൊഡ്യൂൾ സ്ഥാപിക്കും."],
    tags: ["ലോകം", "ബഹിരാകാശം", "ഐഎസ്എസ്"],
    readTime: "4 മിനിറ്റ്",
    comments: 14,
  },
  {
    slug: "world-trade-war",
    title: "ലോക വ്യാപാര യുദ്ധം: രാജ്യങ്ങൾ ചർച്ചയ്ക്ക്",
    titleEn: "Global Trade War: Nations Head to Talks",
    category: "world",
    categoryMl: "അന്തർദേശീയം",
    author: "ലോക വാർത്താ ഡെസ്ക്",
    image: "/uploads/1782973230494-m3qeue.png",
    featured: false,
    media: "standard",
    excerpt: "ലോക വ്യാപാര യുദ്ധത്തിൽ രാജ്യങ്ങൾ ചർച്ചയ്ക്ക് തയ്യാറാകുന്നു.",
    content: "അന്താരാഷ്ട്ര വ്യാപാര സംഘർഷത്തിൽ ചർച്ചകൾ ആരംഭിച്ചു.",
    body: ["അന്താരാഷ്ട്ര വ്യാപാര സംഘർഷത്തിൽ ചർച്ചകൾ ആരംഭിച്ചു."],
    tags: ["ലോകം", "വ്യാപാരം", "യുദ്ധം"],
    readTime: "3 മിനിറ്റ്",
    comments: 7,
  },
  {
    slug: "gulf-remittance-record",
    title: "ഗൾഫ് രാജ്യങ്ങളിൽ നിന്നുള്ള റെമിറ്റൻസ് റെക്കോർഡിൽ",
    titleEn: "Record Remittance from Gulf Countries",
    category: "gulf",
    categoryMl: "ഗൾഫ്",
    author: "ഗൾഫ് ലേഖകൻ",
    image: "/uploads/1782973189113-69z03o.png",
    featured: false,
    media: "standard",
    excerpt: "ഗൾഫ് രാജ്യങ്ങളിൽ നിന്നുള്ള റെമിറ്റൻസ് റെക്കോർഡ് നിലയിൽ.",
    content: "ഇന്ത്യയിലേക്കുള്ള റെമിറ്റൻസ് വർധിച്ചു.",
    body: ["ഇന്ത്യയിലേക്കുള്ള റെമിറ്റൻസ് വർധിച്ചു."],
    tags: ["ഗൾഫ്", "റെമിറ്റൻസ്"],
    readTime: "3 മിനിറ്റ്",
    comments: 10,
  },
  {
    slug: "gulf-housing-project",
    title: "ഗൾഫിൽ പ്രവാസികൾക്ക് പുതിയ ഭവന പദ്ധതി",
    titleEn: "New Housing Project for Expats in Gulf",
    category: "gulf",
    categoryMl: "ഗൾഫ്",
    author: "ഗൾഫ് ലേഖകൻ",
    image: "/uploads/1782973166088-stm7g7.png",
    featured: false,
    media: "standard",
    excerpt: "ഗൾഫ് രാജ്യങ്ങളിൽ പ്രവാസികൾക്ക് പുതിയ ഭവന പദ്ധതി.",
    content: "പ്രവാസി തൊഴിലാളികൾക്ക് താമസ സൗകര്യം വർധിപ്പിക്കും.",
    body: ["പ്രവാസി തൊഴിലാളികൾക്ക് താമസ സൗകര്യം വർധിപ്പിക്കും."],
    tags: ["ഗൾഫ്", "ഭവനം"],
    readTime: "4 മിനിറ്റ്",
    comments: 8,
  },
  {
    slug: "gulf-flight-resumption",
    title: "ഗൾഫ്-കേരള വിമാന സർവീസ് പുനഃരാരംഭിച്ചു",
    titleEn: "Gulf-Kerala Flight Service Resumed",
    category: "gulf",
    categoryMl: "ഗൾഫ്",
    author: "ഗൾഫ് ലേഖകൻ",
    image: "/uploads/1785497721731-6q2k9s.jpg",
    featured: false,
    media: "standard",
    excerpt: "ഗൾഫ്-കേരള വിമാന സർവീസ് വീണ്ടും ആരംഭിച്ചു.",
    content: "കോവിഡിന് ശേഷം ഗൾഫ്-കേരള വിമാന സർവീസ് പൂർണ്ണമായി പുനഃരാരംഭിച്ചു.",
    body: ["കോവിഡിന് ശേഷം ഗൾഫ്-കേരള വിമാന സർവീസ് പൂർണ്ണമായി പുനഃരാരംഭിച്ചു."],
    tags: ["ഗൾഫ്", "വിമാനം"],
    readTime: "3 മിനിറ്റ്",
    comments: 15,
  },
  {
    slug: "gulf-job-fair",
    title: "ഗൾഫ് ജോബ് ഫെയർ: മലയാളികൾക്ക് അവസരം",
    titleEn: "Gulf Job Fair: Opportunities for Malayalis",
    category: "gulf",
    categoryMl: "ഗൾഫ്",
    author: "ഗൾഫ് ലേഖകൻ",
    image: "/uploads/1785497717341-u8h7lq.jpg",
    featured: false,
    media: "standard",
    excerpt: "ഗൾഫ് ജോബ് ഫെയറിൽ മലയാളികൾക്ക് പുതിയ തൊഴിൽ അവസരങ്ങൾ.",
    content: "ഗൾഫ് രാജ്യങ്ങളിലെ കമ്പനികൾ മലയാളി തൊഴിലാളികളെ റിക്രൂട്ട് ചെയ്യുന്നു.",
    body: ["ഗൾഫ് രാജ്യങ്ങളിലെ കമ്പനികൾ മലയാളി തൊഴിലാളികളെ റിക്രൂട്ട് ചെയ്യുന്നു."],
    tags: ["ഗൾഫ്", "തൊഴിൽ"],
    readTime: "3 മിനിറ്റ്",
    comments: 20,
  },
  {
    slug: "sports-olympics-preparation",
    title: "ഒളിമ്പിക്സ് തയ്യാറെടുപ്പ്: ഇന്ത്യൻ താരങ്ങൾ കഠിന പരിശീലനത്തിൽ",
    titleEn: "Olympics Preparation: Indian Athletes in Hard Training",
    category: "sports",
    categoryMl: "കായികം",
    author: "സ്പോർട്സ് ഡെസ്ക്",
    image: "/uploads/1782971889348-bdvjeh.png",
    featured: false,
    media: "standard",
    excerpt: "ഒളിമ്പിക്സിനായി ഇന്ത്യൻ കായിക താരങ്ങൾ പരിശീലനം ശക്തമാക്കി.",
    content: "ഒളിമ്പിക്സ് മെഡൽ നേട്ടത്തിനായി താരങ്ങൾ കഠിന പരിശീലനത്തിൽ.",
    body: ["ഒളിമ്പിക്സ് മെഡൽ നേട്ടത്തിനായി താരങ്ങൾ കഠിന പരിശീലനത്തിൽ."],
    tags: ["കായികം", "ഒളിമ്പിക്സ്"],
    readTime: "4 മിനിറ്റ്",
    comments: 19,
  },
  {
    slug: "sports-ipl-auction",
    title: "ഐപിഎൽ ലേലം: മലയാളി താരങ്ങൾക്ക് ആവേശം",
    titleEn: "IPL Auction: Excitement for Malayali Players",
    category: "sports",
    categoryMl: "കായികം",
    author: "സ്പോർട്സ് ഡെസ്ക്",
    image: "/uploads/1782971857446-qahf7m.png",
    featured: false,
    media: "standard",
    excerpt: "ഐപിഎൽ ലേലത്തിൽ മലയാളി താരങ്ങൾക്ക് വലിയ തുക.",
    content: "ഐപിഎൽ ലേലത്തിൽ മലയാളി ക്രിക്കറ്റ് താരങ്ങൾക്ക് വലിയ തുക ലഭിച്ചു.",
    body: ["ഐപിഎൽ ലേലത്തിൽ മലയാളി ക്രിക്കറ്റ് താരങ്ങൾക്ക് വലിയ തുക ലഭിച്ചു."],
    tags: ["കായികം", "ഐപിഎൽ", "ക്രിക്കറ്റ്"],
    readTime: "3 മിനിറ്റ്",
    comments: 28,
  },
  {
    slug: "sports-kerala-football",
    title: "കേരള ഫുട്ബോൾ ലീഗ്: പുതിയ സീസൺ തുടങ്ങി",
    titleEn: "Kerala Football League: New Season Begins",
    category: "sports",
    categoryMl: "കായികം",
    author: "സ്പോർട്സ് ഡെസ്ക്",
    image: "/uploads/1782969485115-jetk48.jpeg",
    featured: false,
    media: "standard",
    excerpt: "കേരള ഫുട്ബോൾ ലീഗിന്റെ പുതിയ സീസൺ ആരംഭിച്ചു.",
    content: "കേരളത്തിലെ ഫുട്ബോൾ ലീഗ് പുതിയ സീസണിലേക്ക് കടന്നു.",
    body: ["കേരളത്തിലെ ഫുട്ബോൾ ലീഗ് പുതിയ സീസണിലേക്ക് കടന്നു."],
    tags: ["കായികം", "ഫുട്ബോൾ"],
    readTime: "3 മിനിറ്റ്",
    comments: 22,
  },
  {
    slug: "sports-tennis-star",
    title: "ഇന്ത്യൻ ടെന്നീസ് താരം: അന്താരാഷ്ട്ര നേട്ടം",
    titleEn: "Indian Tennis Star: International Achievement",
    category: "sports",
    categoryMl: "കായികം",
    author: "സ്പോർട്സ് ഡെസ്ക്",
    image: "/uploads/1782905411245-8gdtwx.jpeg",
    featured: false,
    media: "standard",
    excerpt: "ഇന്ത്യൻ ടെന്നീസ് താരം അന്താരാഷ്ട്ര ടൂർണമെന്റിൽ നേട്ടം.",
    content: "ഇന്ത്യൻ ടെന്നീസ് താരം അന്താരാഷ്ട്ര റാങ്കിങ്ങിൽ ഉയർന്നു.",
    body: ["ഇന്ത്യൻ ടെന്നീസ് താരം അന്താരാഷ്ട്ര റാങ്കിങ്ങിൽ ഉയർന്നു."],
    tags: ["കായികം", "ടെന്നീസ്"],
    readTime: "3 മിനിറ്റ്",
    comments: 14,
  },
  {
    slug: "business-nifty-record",
    title: "നിഫ്റ്റി റെക്കോർഡ് ഉയരത്തിൽ: നിക്ഷേപകർ ആവേശത്തിൽ",
    titleEn: "Nifty at Record High: Investors Excited",
    category: "business",
    categoryMl: "ബിസിനസ്",
    author: "ബിസിനസ് ലേഖകൻ",
    image: "/uploads/1785500250906-2dxkv2.png",
    featured: false,
    media: "standard",
    excerpt: "ഇന്ത്യൻ ഓഹരി വിപണി റെക്കോർഡ് ഉയരത്തിൽ എത്തി.",
    content: "സെൻസെക്സും നിഫ്റ്റിയും പുതിയ റെക്കോർഡുകൾ സൃഷ്ടിച്ചു.",
    body: ["സെൻസെക്സും നിഫ്റ്റിയും പുതിയ റെക്കോർഡുകൾ സൃഷ്ടിച്ചു."],
    tags: ["ബിസിനസ്", "ഓഹരിവിപണി"],
    readTime: "3 മിനിറ്റ്",
    comments: 16,
  },
  {
    slug: "business-gold-price",
    title: "സ്വർണ വിലയിൽ വൻ വർധന: ആശങ്കയിൽ വിപണി",
    titleEn: "Gold Price Surges: Market in Concern",
    category: "business",
    categoryMl: "ബിസിനസ്",
    author: "ബിസിനസ് ലേഖകൻ",
    image: "/uploads/1782905411245-8gdtwx.jpeg",
    featured: false,
    media: "standard",
    excerpt: "ആഗോള വിപണിയിൽ സ്വർണ വില ഉയർന്നു.",
    content: "സ്വർണ വില റെക്കോർഡ് നിലയിൽ എത്തി.",
    body: ["സ്വർണ വില റെക്കോർഡ് നിലയിൽ എത്തി."],
    tags: ["ബിസിനസ്", "സ്വർണം", "വില"],
    readTime: "3 മിനിറ്റ്",
    comments: 23,
  },
  {
    slug: "business-rupee-dollar",
    title: "രൂപ-ഡോളർ നിരക്കിൽ മാറ്റം: കയറ്റുമതി മേഖലയ്ക്ക് ആശ്വാസം",
    titleEn: "Rupee-Dollar Rate Changes: Relief for Export Sector",
    category: "business",
    categoryMl: "ബിസിനസ്",
    author: "ബിസിനസ് ലേഖകൻ",
    image: "/uploads/1783079636218-3n5wer.png",
    featured: false,
    media: "standard",
    excerpt: "ഇന്ത്യൻ രൂപയുടെ മൂല്യം ഡോളറിനെതിരെ മാറി.",
    content: "രൂപ-ഡോളർ നിരക്കിൽ വലിയ ചാഞ്ചാട്ടം.",
    body: ["രൂപ-ഡോളർ നിരക്കിൽ വലിയ ചാഞ്ചാട്ടം."],
    tags: ["ബിസിനസ്", "രൂപ", "ഡോളർ"],
    readTime: "3 മിനിറ്റ്",
    comments: 11,
  },
  {
    slug: "business-rbi-policy",
    title: "ആർബിഐ നയം: പലിശ നിരക്കിൽ മാറ്റമില്ല",
    titleEn: "RBI Policy: No Change in Interest Rate",
    category: "business",
    categoryMl: "ബിസിനസ്",
    author: "ബിസിനസ് ലേഖകൻ",
    image: "/uploads/1782969485115-jetk48.jpeg",
    featured: false,
    media: "standard",
    excerpt: "ആർബിഐ പലിശ നിരക്കിൽ മാറ്റം വരുത്തിയില്ല.",
    content: "റിസർവ് ബാങ്ക് നയ യോഗത്തിൽ പലിശ നിരക്ക് നിലനിർത്തി.",
    body: ["റിസർവ് ബാങ്ക് നയ യോഗത്തിൽ പലിശ നിരക്ക് നിലനിർത്തി."],
    tags: ["ബിസിനസ്", "ആർബിഐ", "പലിശ"],
    readTime: "3 മിനിറ്റ്",
    comments: 8,
  },
];

async function seed() {
  await connectDB();

  await mongoose.connection.dropDatabase();
  console.log(" Database dropped");

  const passwordHash = await bcrypt.hash("Admin@123", 10);
  await User.create({
    username: "admin",
    email: "admin@malayalamithram.in",
    passwordHash,
    role: "admin",
    name: "Malayalamithram Admin",
  });
  console.log(" Admin user created (admin / Admin@123)");

  await Category.insertMany(categoriesData);
  console.log(` ${categoriesData.length} categories created`);

  const articles = articlesData.map((a, i) => ({
    ...a,
    date: new Date(Date.now() - i * 86400000).toISOString().split("T")[0],
    published: true,
    views: Math.floor(Math.random() * 2000),
    createdAt: new Date(Date.now() - i * 86400000),
  }));
  await Article.insertMany(articles);
  console.log(` ${articles.length} articles created`);

  console.log("\n Seed complete!");
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
